// Generated by CoffeeScript 1.6.3
(function() {
  var ForwardingHandler, Proxy, Q, QProxy;

  Q = require("q");

  Proxy = require("node-proxy");

  ForwardingHandler = require("./forwarding-handler");

  QProxy = function(target) {
    var forwarder;
    forwarder = new ForwardingHandler(target);
    forwarder.get = function(rcvr, name) {
      var _this = this;
      if (typeof this.target[name] === "function" || this.target[name] === void 0) {
        return function() {
          var args;
          args = arguments;
          if (_this.target[name]) {
            return QProxy(Q.when(_this.target, function() {
              return _this.target[name].apply(_this.target, args);
            }));
          } else {
            return QProxy(target.post(name, args));
          }
        };
      } else {
        return this.target[name];
      }
    };
    return Proxy.create(forwarder, Object.getPrototypeOf(target));
  };

  module.exports = QProxy;

}).call(this);
